#!/bin/bash
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

if [ $# -eq 1 ]; then
    REPO_URL=$1
    # Assume $REPO_URL is like "https://github.com/org/repo"
    # and use cut to pull out the "org/repo" part
    ORG_AND_REPO=$(echo "$REPO_URL" | cut -d/ -f4,5)
fi

function setVars() {
    NAME=$1
    VALUE=$2

    echo "setting Secret $NAME in github.com/$ORG_AND_REPO"
    if [ -z "$VALUE" ]; then
        gh secret set "$NAME" --body " " --repo "$ORG_AND_REPO"
    else
        gh secret set "$NAME" --body "$VALUE" --repo "$ORG_AND_REPO"
    fi
}

setVars IMAGE_REGISTRY quay.io/$QUAY_IO_CREDS_USR
setVars IMAGE_REGISTRY_USER $QUAY_IO_CREDS_USR
setVars IMAGE_REGISTRY_PASSWORD $QUAY_IO_CREDS_PSW

setVars ROX_CENTRAL_ENDPOINT $ROX_CENTRAL_ENDPOINT
setVars ROX_API_TOKEN $ROX_API_TOKEN

setVars GITOPS_AUTH_PASSWORD $GITOPS_AUTH_PASSWORD

setVars QUAY_IO_CREDS_USR $QUAY_IO_CREDS_USR
setVars QUAY_IO_CREDS_PSW $QUAY_IO_CREDS_PSW

setVars COSIGN_SECRET_PASSWORD $COSIGN_SECRET_PASSWORD
setVars COSIGN_SECRET_KEY $COSIGN_SECRET_KEY
setVars COSIGN_PUBLIC_KEY $COSIGN_PUBLIC_KEY

setVars TRUSTIFICATION_BOMBASTIC_API_URL "$TRUSTIFICATION_BOMBASTIC_API_URL"
setVars TRUSTIFICATION_OIDC_ISSUER_URL "$TRUSTIFICATION_OIDC_ISSUER_URL"
setVars TRUSTIFICATION_OIDC_CLIENT_ID "$TRUSTIFICATION_OIDC_CLIENT_ID"
setVars TRUSTIFICATION_OIDC_CLIENT_SECRET "$TRUSTIFICATION_OIDC_CLIENT_SECRET"
setVars TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION "$TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION"

gh secret list
