#!/bin/bash
set -euo pipefail

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

SECRET_NAME=$1
SECRET_VALUE=$2

CREDS=$(
    cat << EOF
{
  "": "0",
  "credentials": {
    "scope": "GLOBAL",
    "id": "${SECRET_NAME}",
    "secret": "${SECRET_VALUE}",
    "description": "",
    "\$class": "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
  }
}
EOF
)

echo "Creating Jenkins credential $SECRET_NAME"

curl "${MY_JENKINS_SERVER}/credentials/store/system/domain/_/createCredentials" \
    --user "${MY_JENKINS_USER}:${MY_JENKINS_TOKEN}" \
    --data-urlencode "json=${CREDS}"
