#!/bin/bash
set -euo pipefail

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

SECRET_NAME=$1
USER_NAME=$2
USER_PW=$3

CREDS=$(
    cat << EOF
{
  "": "0",
  "credentials": {
    "scope": "GLOBAL",
    "id": "${SECRET_NAME}",
    "username": "${USER_NAME}",
    "password": "${USER_PW}",
    "description": "",
    "\$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
  }
}
EOF
)

echo "Creating Jenkins credential $SECRET_NAME"

curl "${MY_JENKINS_SERVER}/credentials/store/system/domain/_/createCredentials" \
    --user "${MY_JENKINS_USER}:${MY_JENKINS_TOKEN}" \
    --data-urlencode "json=${CREDS}"
