#!/bin/bash
set -euo pipefail

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

SECRET_NAME=$1

SECRET_INFO="$(curl -s \
    "${MY_JENKINS_SERVER}/credentials/store/system/domain/_/credential/${SECRET_NAME}/api/json" \
    --user "${MY_JENKINS_USER}:${MY_JENKINS_TOKEN}")"

TYPE_NAME="$(echo "${SECRET_INFO}" | jq -r '.typeName')"

if [[ "$TYPE_NAME" =~ ^(S|s)ecret ]]; then
    echo "${SECRET_NAME} with secret <redacted>"
elif [[ "$TYPE_NAME" =~ ^(U|u)sername ]]; then
    username="$(echo "${SECRET_INFO}" | jq -r '.displayName | split("/")[0]')"
    echo "${SECRET_NAME} with user ${username} and password <redacted>"
else
    echo "${SECRET_NAME} with unknown type name: ${TYPE_NAME}"
fi
