#!/bin/bash
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

ENV="MY_JENKINS_SERVER MY_JENKINS_USER MY_JENKINS_BUILD_TOKEN MY_JENKINS_TOKEN"
source $SCRIPTDIR/../rhtap/verify-deps-exist "$ENV" "curl "

PNAME=$1
if [ -z $PNAME ]; then
    echo $0 pipelinename
    exit 0
fi

http_code=$(curl -s -w "%{http_code}" -u $MY_JENKINS_USER:$MY_JENKINS_TOKEN \
    ${MY_JENKINS_SERVER}job/$PNAME/build?token=$MY_JENKINS_BUILD_TOKEN)

echo "Started pipeline $PNAME http_code = $http_code"
